### ISSUE TITLE
more informative "different arguments" message?

### ISSUE THREAD

**Issue by dchudz** [sainathadapa/stubthat#5]
It'd be nice to get a message that has more information than just

> Function is called with arguments different from expected!

(Which argument is different from expected? What's its value? What was expected?)

Maybe there's an easy way to do this that involves using `expect_equal` in your `compare_args` function? The messages from `expect_equal` are quite nice.

**Comment by sainathadapa** [comment]
I agree that `testthat` does the error reporting very good and `stubthat` doesn't do it properly. I looked at the `testthat` code, `expect_equal` and other expects use the `compare` function internally. (https://github.com/hadley/testthat/blob/master/R/compare.R, https://github.com/hadley/testthat/blob/master/R/compare-character.R, https://github.com/hadley/testthat/blob/master/R/compare-numeric.R, https://github.com/hadley/testthat/blob/master/R/compare-time.R) I can import that function, and use it in `compare_args` function, but then the package will depend on `testthat` package. I want to keep the dependencies to zero. I can may be check if `testthat` is installed; if yes, then use `testthat`'s `compare`, otherwise use my simple check function. What do you think?

**Comment by dchudz** [comment]
Your "check if `testthat` is installed" approach seems sensible, although I'm not sure a dependency on `testthat` would be all that bad. Aren't most people going to use them together? (In Python the equivalent functionality is actually provided in one package.)

Another option would be copy-pasting the relevant code from `testthat` (with attribution). The license allows that, and that can be a good way to avoid a dependency when using a small amount of code that's not entangled with the rest of a package.

**Comment by sainathadapa** [comment]
I went ahead and used the `compare` function from the `testthat` package. The messages looks better than before but I'm not entirely satisfied with it. For example, the error message `Component “c”: Mean relative difference: 0.2` doesn't say anything about what is expected and the value with which the function is called. So the best way is to copy the code and modify the `compare` function to suit the needs of `stubthat`.

In the meantime, if you want, you can use the current master branch version of stubthat. It uses `compare` function in place of `isTrue(all.equal(...,...))`.

**Comment by dchudz** [comment]
That's great! Thanks so much!
