### ISSUE TITLE
warning message for unnamed arguments with `...`?

### ISSUE THREAD

**Issue by dchudz** [sainathadapa/stubthat#6]
```
> f <- function(x, ...) print("hi")
> f_stub <- stub(f)
> f_stub$expects(x = 1)
> f_stub$f(1, 2)
Warning message:
In compare_args(data_env$expectations_default$args, called_with_args,  :
  Names of some arguments are just '' (empty string). In such cases, behavior may be unexpected!
```

I identified the source of the problem, but I'm not certain of the best solution:

```
called_with_args        <- c(called_with_args, list(...))
```

When `list(...)` contains any unnamed arguments, the names of the corresponding elements of  `called_with_args` are empty strings.

This check is then triggered:

```
  if (any(names(args_expected) %in% '') || any(names(args_incoming) %in% '')) {
    warning("Names of some arguments are just '' (empty string). In such cases, behavior may be unexpected!")
  }
```

**Comment by dchudz** [comment]
For context, the reason I ran into this is that I'm using stubthat to test package that uses `httr`. `httr` (e.g. `httr::POST`, etc.) makes heavy use of `...` with unnamed arguments.

**Comment by dchudz** [comment]
Or maybe the warning is appropriate. But it'd be nice if such a warning wasn't necessary!

**Comment by sainathadapa** [comment]
I need to order the arguments by name, because in R, unlike many other languages, you can pass arguments to a function in any order, by specifying the name. And if the name is not specified, R will match those values with the unspecified arguments left.

So, in stubthat, for matching the arguments specified in the stub, with the arguments at the time of function call, I use the names of the arguments.

Another flexibility that R gives to developers is the use of '...', using which you can pass unspecified arguments (at the time of constructing the function), while calling the function. And it is possible to send a value to a function without a name, as is happening in the your example.

Currently, this can happen

```
tmp <- function(x, ...) return(1)
stb <- stub(tmp)
stb$expects(x = 1, 2)
stb$f(x = 1, 2) # doesnot throw error
stb$f(x = 1, 2, 3) # throws error
```

The last test above shouldn't throw an error, but because both 2 and 3 values don't have names, and also because of the way I currently handle the matching, the error occurs. Hence the warning. Once I fix issues related to using unnamed arguments, I remove the warning. 

If it is really an issue, I can remove the warning and make a note about in the README for now.

**Comment by dchudz** [comment]
`Once I fix issues related to using unnamed arguments, I remove the warning.`

makes sense
